Added spoolman metrics
scross01/prometheus-klipper-exporter pull request #23
Opened 2024-04-09 12:21 UTC by Forest-Troll

Added metrics from Spoolman module, such as current spool ID and connected status&

2024-04-09 12:53 UTC, scross01 commented
I also use Spoolman with my Klipper install so I will give this a test and provide any feedback.

2024-04-09 13:13 UTC, Forest-Troll commented
I have already do PR to Spoolman with simillar feature. For both it view as:

<img width="1303" alt="Снимок экрана 2024-04-09 в 16 10 08" src="https://github.com/scross01/prometheus-klipper-exporter/assets/46622347/3eeafd80-7721-4fcc-afd0-61d1401db26d">

2024-04-14 11:36 UTC, scross01 requested changes
- [ ] Add comments where highlighted for consistency
- [ ] Add `spoolman` entry in example config `example/prometheus.yml`
- [ ] Update the table with the list of supported metrics in the Modules section of README.md
- [ ] I suggest adding a short section in the README.md specifically covering how the klipper spoolman metrics can be used in conjunction spoolman metrics (https://github.com/Donkie/Spoolman/pull/350)

2024-04-14 11:36 UTC, scross01 commented on collector/collector.go
> +func b2f(cond bool) float64 {
Add a comment before the function definition to explain its purpose (i.e. convert bool to float value)

2024-04-14 11:36 UTC, scross01 commented on collector/collector.go
> +	if slices.Contains(c.modules, "spoolman") {
Add a comment line `// Spoolman` for consistency to other code sections above

2024-04-14 11:36 UTC, scross01 commented on collector/spoolman.go
> +
Add a comment with a link to the relevant section of the moonraker docs
i.e. `// https://moonraker.readthedocs.io/en/latest/web_api/#spoolman-apis`

2026-06-02 00:41 UTC, scross01 commented
Closing the PR, spoolman metrics have been added via a different update in release `v0.15.0`

2026-06-02 00:41 UTC, closed without merging